[features]
seeds = false
[programs.localnet]
nft_marketplace = "BY1FricTncwgkwJELaYEoK49KLWz7HthD2Gjxe64ByfP"

[programs.devnet]
nft_marketplace = "BY1FricTncwgkwJELaYEoK49KLWz7HthD2Gjxe64ByfP"

[programs.mainnet]
nft_marketplace = "BY1FricTncwgkwJELaYEoK49KLWz7HthD2Gjxe64ByfP"

[registry]
url = "https://anchor.projectserum.com"

#[provider]
#cluster = "localnet"
#wallet = "/home/alex/.config/solana/id.json"

#[provider]
#cluster = "devnet"
#wallet = "/home/alex/blockchain/Keys/alex.json"

[provider]
cluster = "mainnet"
wallet = "/home/alex/blockchain/Keys/alex.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
